### ISSUE TITLE
Resultado de las simulaciones no es determinista

### ISSUE THREAD

**Issue by franciscorubin** [javipalanca/taxi_simulator#114]
El resultado de las simulaciones no es determinista, lo cual hace difícil comparar las estrategias utilizadas. 
Es posible añadir como parámetro una seed global que se pueda elegir?

**Comment by javipalanca** [comment]
El no determinismo se debe a que hay varios factores que no se pueden controlar siempre del mismo modo, como la ruta que devolverá el servidor de rutas, por ejemplo, o la latencia de red, que puede hacer que un agente conteste antes que otro. Cara a la competición lo que haremos es repetir varias veces cada simulación y quedarnos con la media.
